FROM ruby:2.4.1
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
ENV path /src/rest-app
RUN mkdir /myapp
WORKDIR /myapp
ADD $path/Gemfile /myapp/Gemfile
ADD $path/Gemfile.lock /myapp/Gemfile.lock
RUN bundle install
ADD $path /myapp
